### ISSUE TITLE
Detect other browsers on Macs and suggest Safari.

### ISSUE THREAD

**Issue by krismeister** [munrocket/parallax-effect#1]
On Mac Chrome (latest) None of the demo pages do paralax.
The example "Background" Shows this error: `TFJS not loaded! ErrorCode=2`

**Comment by munrocket** [comment]
Hello, yea it’s a famous problem that webcam on other browsers in Macs not working at all.

**Comment by krismeister** [comment]
Hm, well I've used my camera on many sites. I'm pretty surprised to hear
you say that.

**Comment by munrocket** [comment]
Are you sure that you not used safari or other app?
https://support.google.com/chrome/thread/13971320?hl=en

Here link for webcam test in browser: https://webcamtests.com/

**Comment by munrocket** [comment]
https://github.com/munrocket/parallax-effect/commit/278bae704e24088407208102f85fbb5d03ec7763 fixed your issue?

**Comment by munrocket** [comment]
Or maybe I need specify source content?
https://webrtc.github.io/samples/src/content/devices/input-output/

**Comment by munrocket** [comment]
Works on macs like сharm.
